# Generated by Django 3.0.6 on 2020-05-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogConfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
