# Generated by Django 3.0.6 on 2020-05-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogConfig', '0002_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='hello world', unique=True),
            preserve_default=False,
        ),
    ]
