# Generated by Django 3.0.6 on 2020-05-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogConfig', '0007_blogpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
    ]
