# Generated by Django 3.0.6 on 2020-06-11 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogConfig', '0030_auto_20200604_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, to='BlogConfig.AppUser'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commen', to='BlogConfig.AppUser'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogConfig.BlogPost')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogConfig.AppUser')),
            ],
        ),
    ]
