# Generated by Django 3.0.6 on 2020-06-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogConfig', '0031_auto_20200611_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes', to='BlogConfig.AppUser'),
        ),
    ]
